name: Create and publish a Docker image

on:
  schedule:
    - cron:  '0 0 * * *'


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: 'IBM/staticroute-operator'

      - name: Get commit sha from IBM/staticroute-operator repo
        id: get_commit_sha
        run: echo "IBM_COMMIT_SHA_SHORT=$(git rev-parse --short HEAD | cut -c 1-6)" >> $GITHUB_OUTPUT


      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: "${{ env.REGISTRY }}/${{ github.actor }}/ibm-staticroute-operator:${{ steps.get_commit_sha.outputs.IBM_COMMIT_SHA_SHORT }}"
          build-args: BUILDER_IMAGE=golang